<a href="https://colab.research.google.com/github/MaksimNEF/Euler_Tasks/blob/master/Lesson_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Dataframe
df = pd.DataFrame({
    'Имя' : ["Анна", "Борис", "Вика"],
    'Возраст': [25,40,28],
    'Город' : ['Москва', 'СПБ', 'Казань']
})
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1  Борис       40     СПБ
2   Вика       28  Казань

In [ ]:
# Метод выводит несколько строк
df.head(2)

     Имя  Возраст   Город
0   Анна       25  Москва
1  Борис       40     СПБ

In [ ]:
df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Имя      3 non-null      object
 1   Возраст  3 non-null      int64
 2   Город    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
df.describe()

         Возраст
count   3.000000
mean   31.000000
std     7.937254
min    25.000000
25%    26.500000
50%    28.000000
75%    34.000000
max    40.000000

In [ ]:
# df[['Имя','Город']]
# df.iloc[0]
# Можно писать сложнве условия
# df[df['Возраст'] > 28]
df[df['Возраст'] > 28 & (df['Город'] == 'СПБ')]
df.query('Возраст > 25 and Город == "Казань"')

    Имя  Возраст   Город
2  Вика       28  Казань

In [ ]:
df['Зарплата'] = [70000, 80888, 75000]
df['Возраст_через_10'] = df['Возраст'] + 10
df

     Имя  Возраст   Город  Зарплата  Возраст_через_10
0   Анна       25  Москва     70000                35
1  Борис       40     СПБ     80888                50
2   Вика       28  Казань     75000                38

In [ ]:
# df.drop('Возраст_через_10', axis=1 , inplace=True)
# del df['Зарплата']
df

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     70000
1  Борис       40     СПБ     80888
2   Вика       28  Казань     75000

In [ ]:
df_nan = pd.DataFrame({
    'A':[1,np.nan,3],
    'B':[5,6,np.nan]
})
# df_nan.isnull()
# df_nan.notnull()
# df_nan.dropna()
# df_nan.fillna(0)
df_nan.fillna(df_nan.mean())

     A    B
0  1.0  5.0
1  2.0  6.0
2  3.0  5.5

In [ ]:
# Фильтрация и сортировка
df['Город'].unique()
df['Город'].value_counts()
df.sort_values('Возраст',ascending=False)
df.sort_index()

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     70000
1  Борис       40     СПБ     80888
2   Вика       28  Казань     75000

In [ ]:
data = pd.DataFrame({
    'Отдел' :['IT','HR','IT','IT','HR'],
    'Сотрудник' :['Анна',"Борис", "Вика", "Глеб" ,"Дима"],
    "Зарплата" : [100,80,110,150,120]
})

data.groupby('Отдел')['Зарплата'].mean()
data.groupby('Отдел')['Зарплата'].agg(['mean','max','min','count'])

        mean  max  min  count
Отдел
HR     100.0  120   80      2
IT     100.0  110   90      3

In [ ]:
data.groupby(['Отдел','Зарплата']).size()
data.groupby('Отдел').agg({
    'Зарплата':'mean',
    'Сотрудник': 'count'
})

       Зарплата  Сотрудник
Отдел
HR        100.0          2
IT        100.0          3